```{r}
x <- c(184, 170, 180)
y <- c(85, 70, 82)

mean(x)
mean(y)
```

```{r}
cov(x,y)
```

[문제] 학생 10명의 키와 몸무게를 측정한 자료이다. 자료를 분석하여 키와 몸무게의 선형관계를 나타내는 상관계수를 구하고, 그 유의성을 유의수준(@) 0.05에서 검정하세요.
```{r}
height <- c(176 , 172, 182, 160, 163, 165, 168, 163, 182, 182)
weight <- c(72,72,70,43,48,54,51,52,73,88)

mean(height)
mean(weights)
plot(height, weight)
```

```{r}
cov(height,weight)
cor(height, weight)
```

가설검정
H0(귀무가설): 키와 몸무게 간에는 선형관계가 없다(상관계수는 0이다)
H1(대립가설, 연구가설): 키와 몸무게간에는 선형관계가 있다.(상관계수는 0이 아니다)
유의수준 0.05
t분포의 자유도  n-2
df = 10 - 2 = 8

결과해석
유의수준 0.05로 하여 검정한 결과 검정통계량 t값(6.207)이 우측 임계치(2.306)보다 크므로 귀무가설을 기각하고 대립가설을 채택한다. 키와 몸무게의 상관계수 0.91은 5% 유의수준에서 검정한 결과 통계적으로 유의하다.


```{r}
cor.test(height, weight, method='pearson', alternative='two.sided')
```
two.sided
last

```{r}
# y = ax + b
a = cov(weight, height) / var(height)
y = mean(weight)
x = mean(height)
b = y - (a*x)
```

```{r}
(a*185)+b
```

```{r}
lm(weight ~ height) # linear model lm(종속변수 ~ 독립변수)
```

```{r}
y = 1.519 * 185 - 197.902
y
```

```{r}
score <-read.table('C:/Users/stu/git/DA_Academy/data/score.txt', header=T, sep=',')
score
```

```{r}
attach(score) #해당 데이터프레임의 컬럼에 접근할 때 데이터프레임 명 생략 가능
# 공분산
cov(IQ, 성적)

# 상관계수
cov(IQ, 성적) / (sd(IQ)*sd(성적))
cor(IQ, 성적)
```

```{r}
#회귀분석
l <- lm(성적 ~ IQ)
l
```

IQ 130 일때 시험성적 예측
```{r}
0.6714*130 -5.2918
```

```{r}
plot(IQ, 성적, pch=20, col='red')
abline(l, col='blue')
```

```{r}
coef(l)
```

```{r}
cor(성적, 다니는학원수)
# 단순회귀분석
lm(성적 ~ 다니는학원수)
```

```{r}
# 다중회귀분석
lm(성적 ~ IQ+다니는학원수+게임하는시간+TV시청시간)
```

```{r}
(135*0.4684) + (5*0.7179) + (1*-9.8390) + (1*-1.3854) + 23.2992
```

